### ISSUE TITLE
Delete the Python 2.7 Windows packages

### ISSUE THREAD

**Issue by ajgpitch** [conda-forge/qutip-feedstock#20]
Is it possible to delete packages? 
As discussed in #16 all the packages for Windows, except the python 3.5+ packages, break Python when the qutip library is imported. As it is seemingly not possible to fix this issue and supersede them, then we would like to remove the packages. @isuruf is this possible? I can't find anything about it online.

**Comment by isuruf** [comment]
Yes, this is possible. Only @conda-forge/core have access to do that.

**Comment by ocefpaf** [comment]
I will move them to a `broken` label instead of removing. However, we can remove them if there is 100% certainty (which seems to be the case here) that no one will need those.

**Comment by ocefpaf** [comment]
Done. Please let me know if I got them all: https://anaconda.org/conda-forge/qutip/files?sort=basename&version=&sort_order=desc&page=3&channel=broken

**Comment by ajgpitch** [comment]
Yes, that certainly looks like all of them in that link. 
However, when I do a `conda search qutip` on Windows I still see them all?

**Comment by ocefpaf** [comment]
But you should not be able to install them unless you use the `broken` channel.

**Comment by ajgpitch** [comment]
Ok, I just did another search, and all the Python 2.7 ones have gone on Windows. So that's great, thank you.
The Python 3.4 ones are also broken, can we bin those too please?

**Comment by ocefpaf** [comment]
Yes :weary:  ( :stuck_out_tongue_winking_eye: )

**Comment by ocefpaf** [comment]
Should be OK now can you double check?

**Comment by ajgpitch** [comment]
Only working packages available now. 
Great. Thank you
